/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 22
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE_PERCENT = 1,
  aux_sym_jinja_statement_token1 = 2,
  aux_sym_jinja_statement_token2 = 3,
  anon_sym_PERCENT_RBRACE = 4,
  anon_sym_LBRACE_LBRACE = 5,
  aux_sym_jinja_expression_token1 = 6,
  aux_sym_jinja_expression_token2 = 7,
  anon_sym_RBRACE_RBRACE = 8,
  anon_sym_LBRACE_POUND = 9,
  aux_sym_jinja_comment_token1 = 10,
  aux_sym_jinja_comment_token2 = 11,
  anon_sym_POUND_RBRACE = 12,
  aux_sym_content_token1 = 13,
  aux_sym_content_token2 = 14,
  sym_source_file = 15,
  sym_jinja_statement = 16,
  sym_jinja_expression = 17,
  sym_jinja_comment = 18,
  sym_content = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym_jinja_statement_repeat1 = 21,
  aux_sym_jinja_expression_repeat1 = 22,
  aux_sym_jinja_comment_repeat1 = 23,
  aux_sym_content_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE_PERCENT] = "{%",
  [aux_sym_jinja_statement_token1] = "jinja_statement_token1",
  [aux_sym_jinja_statement_token2] = "jinja_statement_token2",
  [anon_sym_PERCENT_RBRACE] = "%}",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [aux_sym_jinja_expression_token1] = "jinja_expression_token1",
  [aux_sym_jinja_expression_token2] = "jinja_expression_token2",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_LBRACE_POUND] = "{#",
  [aux_sym_jinja_comment_token1] = "jinja_comment_token1",
  [aux_sym_jinja_comment_token2] = "jinja_comment_token2",
  [anon_sym_POUND_RBRACE] = "#}",
  [aux_sym_content_token1] = "content_token1",
  [aux_sym_content_token2] = "content_token2",
  [sym_source_file] = "source_file",
  [sym_jinja_statement] = "jinja_statement",
  [sym_jinja_expression] = "jinja_expression",
  [sym_jinja_comment] = "jinja_comment",
  [sym_content] = "content",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_jinja_statement_repeat1] = "jinja_statement_repeat1",
  [aux_sym_jinja_expression_repeat1] = "jinja_expression_repeat1",
  [aux_sym_jinja_comment_repeat1] = "jinja_comment_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE_PERCENT] = anon_sym_LBRACE_PERCENT,
  [aux_sym_jinja_statement_token1] = aux_sym_jinja_statement_token1,
  [aux_sym_jinja_statement_token2] = aux_sym_jinja_statement_token2,
  [anon_sym_PERCENT_RBRACE] = anon_sym_PERCENT_RBRACE,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [aux_sym_jinja_expression_token1] = aux_sym_jinja_expression_token1,
  [aux_sym_jinja_expression_token2] = aux_sym_jinja_expression_token2,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_LBRACE_POUND] = anon_sym_LBRACE_POUND,
  [aux_sym_jinja_comment_token1] = aux_sym_jinja_comment_token1,
  [aux_sym_jinja_comment_token2] = aux_sym_jinja_comment_token2,
  [anon_sym_POUND_RBRACE] = anon_sym_POUND_RBRACE,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [aux_sym_content_token2] = aux_sym_content_token2,
  [sym_source_file] = sym_source_file,
  [sym_jinja_statement] = sym_jinja_statement,
  [sym_jinja_expression] = sym_jinja_expression,
  [sym_jinja_comment] = sym_jinja_comment,
  [sym_content] = sym_content,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_jinja_statement_repeat1] = aux_sym_jinja_statement_repeat1,
  [aux_sym_jinja_expression_repeat1] = aux_sym_jinja_expression_repeat1,
  [aux_sym_jinja_comment_repeat1] = aux_sym_jinja_comment_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_jinja_statement_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_jinja_statement_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_jinja_expression_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_jinja_expression_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_jinja_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_jinja_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_jinja_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_jinja_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_jinja_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_jinja_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_jinja_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_jinja_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '{') ADVANCE(2);
      if (lookahead == '}') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '%') ADVANCE(10);
      if (lookahead == '{') ADVANCE(15);
      if (lookahead != 0) ADVANCE(27);
      END_STATE();
    case 3:
      if (lookahead == '%') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == '}') ADVANCE(24);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == '}') ADVANCE(14);
      if (lookahead != 0) ADVANCE(13);
      END_STATE();
    case 6:
      if (lookahead == '}') ADVANCE(19);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == '}') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '{') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_jinja_statement_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(12);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_jinja_statement_token1);
      if (lookahead != 0 &&
          lookahead != '%') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_jinja_statement_token2);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_jinja_expression_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_jinja_expression_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_jinja_expression_token2);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LBRACE_POUND);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_jinja_comment_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_jinja_comment_token1);
      if (lookahead != 0 &&
          lookahead != '#') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_jinja_comment_token2);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_POUND_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_content_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(25);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_content_token2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 8},
  [3] = {.lex_state = 8},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(1),
    [aux_sym_jinja_statement_token2] = ACTIONS(1),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [aux_sym_jinja_expression_token2] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_POUND] = ACTIONS(1),
    [aux_sym_jinja_comment_token2] = ACTIONS(1),
    [anon_sym_POUND_RBRACE] = ACTIONS(1),
    [aux_sym_content_token2] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(21),
    [sym_jinja_statement] = STATE(2),
    [sym_jinja_expression] = STATE(2),
    [sym_jinja_comment] = STATE(2),
    [sym_content] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACE_POUND] = ACTIONS(9),
    [aux_sym_content_token1] = ACTIONS(11),
    [aux_sym_content_token2] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(11), 1,
      aux_sym_content_token1,
    ACTIONS(13), 1,
      aux_sym_content_token2,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      aux_sym_content_repeat1,
    STATE(3), 5,
      sym_jinja_statement,
      sym_jinja_expression,
      sym_jinja_comment,
      sym_content,
      aux_sym_source_file_repeat1,
  [29] = 8,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    ACTIONS(19), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(22), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(25), 1,
      anon_sym_LBRACE_POUND,
    ACTIONS(28), 1,
      aux_sym_content_token1,
    ACTIONS(31), 1,
      aux_sym_content_token2,
    STATE(4), 1,
      aux_sym_content_repeat1,
    STATE(3), 5,
      sym_jinja_statement,
      sym_jinja_expression,
      sym_jinja_comment,
      sym_content,
      aux_sym_source_file_repeat1,
  [58] = 5,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      aux_sym_content_token1,
    ACTIONS(40), 1,
      aux_sym_content_token2,
    STATE(5), 1,
      aux_sym_content_repeat1,
    ACTIONS(36), 3,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
  [76] = 5,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 1,
      aux_sym_content_token1,
    ACTIONS(49), 1,
      aux_sym_content_token2,
    STATE(5), 1,
      aux_sym_content_repeat1,
    ACTIONS(44), 3,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
  [94] = 2,
    ACTIONS(52), 2,
      ts_builtin_sym_end,
      aux_sym_content_token1,
    ACTIONS(54), 4,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
      aux_sym_content_token2,
  [105] = 2,
    ACTIONS(56), 2,
      ts_builtin_sym_end,
      aux_sym_content_token1,
    ACTIONS(58), 4,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
      aux_sym_content_token2,
  [116] = 2,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      aux_sym_content_token1,
    ACTIONS(62), 4,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
      aux_sym_content_token2,
  [127] = 2,
    ACTIONS(64), 2,
      ts_builtin_sym_end,
      aux_sym_content_token1,
    ACTIONS(66), 4,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
      aux_sym_content_token2,
  [138] = 2,
    ACTIONS(68), 2,
      ts_builtin_sym_end,
      aux_sym_content_token1,
    ACTIONS(70), 4,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
      aux_sym_content_token2,
  [149] = 2,
    ACTIONS(72), 2,
      ts_builtin_sym_end,
      aux_sym_content_token1,
    ACTIONS(74), 4,
      anon_sym_LBRACE_PERCENT,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_POUND,
      aux_sym_content_token2,
  [160] = 4,
    ACTIONS(76), 1,
      aux_sym_jinja_expression_token1,
    ACTIONS(78), 1,
      aux_sym_jinja_expression_token2,
    ACTIONS(80), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(16), 1,
      aux_sym_jinja_expression_repeat1,
  [173] = 4,
    ACTIONS(82), 1,
      aux_sym_jinja_comment_token1,
    ACTIONS(84), 1,
      aux_sym_jinja_comment_token2,
    ACTIONS(86), 1,
      anon_sym_POUND_RBRACE,
    STATE(18), 1,
      aux_sym_jinja_comment_repeat1,
  [186] = 4,
    ACTIONS(88), 1,
      aux_sym_jinja_statement_token1,
    ACTIONS(90), 1,
      aux_sym_jinja_statement_token2,
    ACTIONS(92), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(15), 1,
      aux_sym_jinja_statement_repeat1,
  [199] = 4,
    ACTIONS(94), 1,
      aux_sym_jinja_statement_token1,
    ACTIONS(96), 1,
      aux_sym_jinja_statement_token2,
    ACTIONS(98), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(17), 1,
      aux_sym_jinja_statement_repeat1,
  [212] = 4,
    ACTIONS(100), 1,
      aux_sym_jinja_expression_token1,
    ACTIONS(102), 1,
      aux_sym_jinja_expression_token2,
    ACTIONS(104), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(19), 1,
      aux_sym_jinja_expression_repeat1,
  [225] = 4,
    ACTIONS(106), 1,
      aux_sym_jinja_statement_token1,
    ACTIONS(109), 1,
      aux_sym_jinja_statement_token2,
    ACTIONS(112), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(17), 1,
      aux_sym_jinja_statement_repeat1,
  [238] = 4,
    ACTIONS(114), 1,
      aux_sym_jinja_comment_token1,
    ACTIONS(116), 1,
      aux_sym_jinja_comment_token2,
    ACTIONS(118), 1,
      anon_sym_POUND_RBRACE,
    STATE(20), 1,
      aux_sym_jinja_comment_repeat1,
  [251] = 4,
    ACTIONS(120), 1,
      aux_sym_jinja_expression_token1,
    ACTIONS(123), 1,
      aux_sym_jinja_expression_token2,
    ACTIONS(126), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(19), 1,
      aux_sym_jinja_expression_repeat1,
  [264] = 4,
    ACTIONS(128), 1,
      aux_sym_jinja_comment_token1,
    ACTIONS(131), 1,
      aux_sym_jinja_comment_token2,
    ACTIONS(134), 1,
      anon_sym_POUND_RBRACE,
    STATE(20), 1,
      aux_sym_jinja_comment_repeat1,
  [277] = 1,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 76,
  [SMALL_STATE(6)] = 94,
  [SMALL_STATE(7)] = 105,
  [SMALL_STATE(8)] = 116,
  [SMALL_STATE(9)] = 127,
  [SMALL_STATE(10)] = 138,
  [SMALL_STATE(11)] = 149,
  [SMALL_STATE(12)] = 160,
  [SMALL_STATE(13)] = 173,
  [SMALL_STATE(14)] = 186,
  [SMALL_STATE(15)] = 199,
  [SMALL_STATE(16)] = 212,
  [SMALL_STATE(17)] = 225,
  [SMALL_STATE(18)] = 238,
  [SMALL_STATE(19)] = 251,
  [SMALL_STATE(20)] = 264,
  [SMALL_STATE(21)] = 277,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jinja_statement, 2, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jinja_statement, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jinja_expression, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jinja_expression, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jinja_comment, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jinja_comment, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jinja_expression, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jinja_expression, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jinja_statement, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jinja_statement, 3, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jinja_comment, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jinja_comment, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_jinja_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jinja_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_jinja_statement_repeat1, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_jinja_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [123] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jinja_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_jinja_expression_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_jinja_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_jinja_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_jinja_comment_repeat1, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jinja2(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "jinja2",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
